name: Sync to GLiNet-Community-Scripts

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to org repo
        env:
          ORG_TOKEN: ${{ secrets.ORG_SYNC_TOKEN }}
        run: |
          git config --global user.email "vlord3@gmail.com"
          git config --global user.name "phantasm22"
          git remote add community https://x-access-token:${ORG_TOKEN}@github.com/GLiNet-Community-Scripts/OpenSpeedTestServer.git
          git push community main --force
